- name: Get Package from Nexus 
  hosts: nexus
  become: yes
  tasks:
    - name: Download latest VProfile.war from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{groupid}}/{{time}}/{{build}}/{{vprofile_version}}"
        dest: "/tmp/vproapp-{{vprofile_version}}"
      
